name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    -name: list file
      run: ls -la
    - name: compile c program
      run: gcc -o main main.c
    - name: result
      run: ./main
